# -*- coding: utf-8 -*-
"""Preprocessing final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxEJffjV7StoOEBgwgwwrAMAe2-v5dco
"""

import os
os.environ['KAGGLE_USERNAME'] = 'LAKS'
os.environ['KAGGLE_KEY'] = 'a6a2b9707ce76328776751bd3eccf386'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip yasserh/titanic-dataset -d /content/titanic

import pandas as pd
df = pd.read_csv("/content/titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

print(df.columns)

print(df['Survived'])

df.drop('Fare', axis=1, inplace=True)
print(df)

print(df['Age'].median())

df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
print(df[['Age']].head(10))
print(df['Age'].isnull().sum())

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

print(df['Embarked'].head(10))
print(df['Embarked'].isnull().sum())

df['HasCabin'] = df['Cabin'].notnull().astype(int)
df.drop('Cabin', axis=1, inplace=True)

df.drop_duplicates(inplace=True)
print(df)

df['Sex'] = df['Sex'].map({'male':0, 'female':1})

print(df)

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

print(df['FamilySize'])

df.drop(['Ticket', 'PassengerId'], axis=1, inplace=True)

df.head()
df.info()

df.isnull().sum()

import matplotlib.pyplot as plt
plt.hist(df['Age'], bins=10, color='skyblue', edgecolor='black')
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt

plt.boxplot(df['Fare'])
plt.title('Outlier Detection using Boxplot (Fare)')
plt.ylabel('Fare')
plt.show()

plt.scatter(df['PassengerId'], df['FamilySize'], colours='red')
plt.xlabel('PassengerId')
plt.ylabel('FamilySize')
plt.title('Passengerid vs FamilySize')
plt.show()

df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

df.drop(['Ticket', 'PassengerId', 'Name'], axis=1, inplace=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
print("Model Trained")
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(cm)
print("Classification Report:")
print(report)

#IQR=q3-q1
#lowerbound=q1-1.5*IQR
#upperbound=q3-1.5*IQR
#IQR fullform - interquartile range
import matplotlib.pyplot as plt
plt.boxplot(df['Fare'])
plt.title('Outlier Detection using Boxplot (Fare)')
plt.ylabel('Fare')
plt.show()