# -*- coding: utf-8 -*-
"""pythonTT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQILhy19M0Fr5aYq2ld__7c2NL-I4p3P
"""

#1
n=int(input())
if n % 2 == 0:
  print("even")
else:
  print("odd")

#2
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("leap")
else:
    print("not leap")

#3
n=int(input())
if n>0 :
  print("pos")
elif n<0:
  print("neg")
else:
  print("zero")

#4
s1=input()
s2=input()
if sorted(s1) == sorted(s2):
  print("anagram")
else:
  print("not anagram")

#5
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#6
for i in range(1,6):
  print("*"*i)

#7
n=6
for i in range(n):
  print(" " * i + "*" * (n-i))

#8
n=3
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)
for i in range(n-1 , 0 , -1):
  print(" " * (n-i) + "* " * i)

#9
n=6
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)

#10
numbers = [10, 5, 20, 15, 30, 25, 40, 35]
sorted_numbers = sorted(numbers, reverse=True)
largest_three = sorted_numbers[:3]
print(f"Original list: {numbers}")
print(f"Largest three numbers: {largest_three}")

#11
s1=input()
s2=input()
s1vals=[]
s2vals=[]
s1len=len(s1)
s2len=len(s2)
count=0
for s in s1:
  s1vals.append(s)
for s in s2:
  s2vals.append(s)
for s in s1vals:
    if all(x in s2vals for x in s1vals)==True:
      count+=1
if(count==s1len or count==s2len) and (s1len==s2len):
  print("Anagram")
else:
  print("Not anagram")

#12
n=int(input())
x=list(map(int,input().split()))
for i in range(1,n+1):
  d=x[i]
  if(x[i]==0):
    d=x[i-1] + 1
    print(d)
    break

#13
s=input()
palin=""
for i in range(len(s)):
  for j in range(i-1,len(s)+1):
    x=s[i:j]
    if x==x[::-1] and len(x) > len(palin) and x != s:
      palin=x
print(palin)

#14
s=input()
count=0
subs=set()
i=0
for j in range(len(s)):
  while s[j] in subs:
    subs.remove(s[i])
    i += 1
  subs.add(s[j])
  count = max(count, j - i + 1)
print(count)

#15
s1=input()
s2=input()
count=0
if(len(s1)!=len(s2)):
  print("No")
else:
  for i in range(len(s1)):
    if(s1[i]!=s2[i]):
      count+=1
  if(count==1):
    print("Yes")
  else:
    print("No")

#16
s=input()
v="aeiou"
pos=[]
vol=[]
for i in range(len(s)):
  if s[i] in v:
    pos.append(i)
    vol.append(s[i])
vol.reverse()
s=list(s)
for i in range(len(pos)):
  s[pos[i]] = vol[i]
print("".join(s))

#17classes and objects
class Student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("Name:",self.name)
    print("age:",self.age)
obj= Student("ABC",3)
obj.display()

#18#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj=son()
obj.bike()

#19class father:
  def property(self):
    print("father property")
class son(father):
  pass
obj=son()
obj.property()

#20#polymorphism(method overriding)
class animal:
  def sound(self):
    print("animal makes sound")
class dog(animal):
  def sound(sef):
    print("dog barks")
obj=dog()
obj.sound()

#21#abstraction
class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance:",self.__balance)
obj=bank()
obj.show_balance()

#22
class Multiply:
  def product(self, a=None, b=None, c=None):
    if a is not None and b is not None and c is not None:
      print("product=",a*b*c)
    elif a is not None and b is not None:
      print("product=",a*b)
    else:
      print("invalid")
obj=Multiply()
obj.product(2,3)
obj.product(2,3,4)

#23
n = 13
is_n_prime = n > 1 and all(n % i for i in range(2, int(n**0.5) + 1))
reversed_n = int(str(n)[::-1])
is_reversed_n_prime = reversed_n > 1 and all(reversed_n % i for i in range(2, int(reversed_n**0.5) + 1))

if is_n_prime: print(f"{n} is an emirp (reverse {reversed_n} also prime)." if is_reversed_n_prime and n != reversed_n else (f"{n} is a palindromic prime." if n == reversed_n else f"{n} is prime, but reverse {reversed_n} is not."))
else: print(f"{n} is not prime.")

#24
n=int(input())
for i in range(1,n+1):
  if(i%2==0):
    print(f"-{i}")
  else:
    print(i)

#25
n = 13
is_n_prime = n > 1 and all(n % i for i in range(2, int(n**0.5) + 1))
reversed_n = int(str(n)[::-1])
is_reversed_n_prime = reversed_n > 1 and all(reversed_n % i for i in range(2, int(reversed_n**0.5) + 1))

else: print(f"{n} is not prime.")

#26
n = int(input())

a = str(n*n)[::-1]
b = str(int(str(n)[::-1])**2)

if a == b:
    print("Adam Number")
else:
    print("Not Adam Number")

#28
n = input()
for i in range(len(n)):
    x = int(n[i:] + n[:i])
    for j in range(2,x):
        if x % j == 0:
            print("Not Circular prime")
print("Circular Prime")

#29
n = input()
if '0' in n:
    print('Duck Number')
else:
    print('Not a Duck Number')

#30
n = int(input())
temp = n
s = 0
while temp > 0:
    digit = temp % 10
    fact = 1
    i = 1
    while i <= digit:
        fact = fact * i
        i = i + 1
    s = s + fact
    temp = temp // 10
if s == n:
    print("Peterson Number")
else:
    print("Not a Peterson Number")

#31
s = input()
for i in range(len(s)):
    t = s[:i] + s[i+1:]
    if t == t[::-1]:
        print("YES")
        break
else:
    print("NO")

#32
n = int(input())
sq = n * n
if sq % 10 == n % 10:
    print("Automorphic Number")
else:
    print("Not an Automorphic Number")

#33
n = int(input())
arr = list(map(int, input().split()))
total = n * (n + 1) // 2
print(total - sum(arr))

#34
arr = list(map(int, input().split()))
seen = []
for x in arr:
    if x in seen:
        break
    seen.append(x)
if duplicate:
    print("Duplicate Found")
else:
    print("No Duplicate")