# -*- coding: utf-8 -*-
"""pythonTT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQILhy19M0Fr5aYq2ld__7c2NL-I4p3P
"""

#1
n=int(input())
if n % 2 == 0:
  print("even")
else:
  print("odd")

#2
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("leap")
else:
    print("not leap")

#3
n=int(input())
if n>0 :
  print("pos")
elif n<0:
  print("neg")
else:
  print("zero")

#4
s1=input()
s2=input()
if sorted(s1) == sorted(s2):
  print("anagram")
else:
  print("not anagram")

#5
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#6
for i in range(1,6):
  print("*"*i)

#7
n=6
for i in range(n):
  print(" " * i + "*" * (n-i))

#8
n=3
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)
for i in range(n-1 , 0 , -1):
  print(" " * (n-i) + "* " * i)

#9
n=6
for i in range(1,n+1):
  print(" " * (n-i) + "* " * i)

#10
numbers = [10, 5, 20, 15, 30, 25, 40, 35]
sorted_numbers = sorted(numbers, reverse=True)
largest_three = sorted_numbers[:3]
print(f"Original list: {numbers}")
print(f"Largest three numbers: {largest_three}")

#11
s1=input()
s2=input()
s1vals=[]
s2vals=[]
s1len=len(s1)
s2len=len(s2)
count=0
for s in s1:
  s1vals.append(s)
for s in s2:
  s2vals.append(s)
for s in s1vals:
    if all(x in s2vals for x in s1vals)==True:
      count+=1
if(count==s1len or count==s2len) and (s1len==s2len):
  print("Anagram")
else:
  print("Not anagram")

#12
n=int(input())
x=list(map(int,input().split()))
for i in range(1,n+1):
  d=x[i]
  if(x[i]==0):
    d=x[i-1] + 1
    print(d)
    break

#13
s=input()
palin=""
for i in range(len(s)):
  for j in range(i-1,len(s)+1):
    x=s[i:j]
    if x==x[::-1] and len(x) > len(palin) and x != s:
      palin=x
print(palin)

#14
s=input()
count=0
subs=set()
i=0
for j in range(len(s)):
  while s[j] in subs:
    subs.remove(s[i])
    i += 1
  subs.add(s[j])
  count = max(count, j - i + 1)
print(count)

#15
s1=input()
s2=input()
count=0
if(len(s1)!=len(s2)):
  print("No")
else:
  for i in range(len(s1)):
    if(s1[i]!=s2[i]):
      count+=1
  if(count==1):
    print("Yes")
  else:
    print("No")

#16
s=input()
v="aeiou"
pos=[]
vol=[]
for i in range(len(s)):
  if s[i] in v:
    pos.append(i)
    vol.append(s[i])
vol.reverse()
s=list(s)
for i in range(len(pos)):
  s[pos[i]] = vol[i]
print("".join(s))

#17classes and objects
class Student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print("Name:",self.name)
    print("age:",self.age)
obj= Student("ABC",3)
obj.display()

#18#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj=son()
obj.bike()

#19class father:
  def property(self):
    print("father property")
class son(father):
  pass
obj=son()
obj.property()

#20#polymorphism(method overriding)
class animal:
  def sound(self):
    print("animal makes sound")
class dog(animal):
  def sound(sef):
    print("dog barks")
obj=dog()
obj.sound()

#21#abstraction
class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance:",self.__balance)
obj=bank()
obj.show_balance()

#22
class Multiply:
  def product(self, a=None, b=None, c=None):
    if a is not None and b is not None and c is not None:
      print("product=",a*b*c)
    elif a is not None and b is not None:
      print("product=",a*b)
    else:
      print("invalid")
obj=Multiply()
obj.product(2,3)
obj.product(2,3,4)

#23
n = 13
is_n_prime = n > 1 and all(n % i for i in range(2, int(n**0.5) + 1))
reversed_n = int(str(n)[::-1])
is_reversed_n_prime = reversed_n > 1 and all(reversed_n % i for i in range(2, int(reversed_n**0.5) + 1))

if is_n_prime: print(f"{n} is an emirp (reverse {reversed_n} also prime)." if is_reversed_n_prime and n != reversed_n else (f"{n} is a palindromic prime." if n == reversed_n else f"{n} is prime, but reverse {reversed_n} is not."))
else: print(f"{n} is not prime.")

#24
n=int(input())
for i in range(1,n+1):
  if(i%2==0):
    print(f"-{i}")
  else:
    print(i)

#25
n = 13
is_n_prime = n > 1 and all(n % i for i in range(2, int(n**0.5) + 1))
reversed_n = int(str(n)[::-1])
is_reversed_n_prime = reversed_n > 1 and all(reversed_n % i for i in range(2, int(reversed_n**0.5) + 1))

else: print(f"{n} is not prime.")

#26
n = int(input())

a = str(n*n)[::-1]
b = str(int(str(n)[::-1])**2)

if a == b:
    print("Adam Number")
else:
    print("Not Adam Number")

#28
n = input()
for i in range(len(n)):
    x = int(n[i:] + n[:i])
    for j in range(2,x):
        if x % j == 0:
            print("Not Circular prime")
print("Circular Prime")

#29
n = input()
if '0' in n:
    print('Duck Number')
else:
    print('Not a Duck Number')

#30
n = int(input())
temp = n
s = 0
while temp > 0:
    digit = temp % 10
    fact = 1
    i = 1
    while i <= digit:
        fact = fact * i
        i = i + 1
    s = s + fact
    temp = temp // 10
if s == n:
    print("Peterson Number")
else:
    print("Not a Peterson Number")

#31
s = input()
for i in range(len(s)):
    t = s[:i] + s[i+1:]
    if t == t[::-1]:
        print("YES")
        break
else:
    print("NO")

#32
n = int(input())
sq = n * n
if sq % 10 == n % 10:
    print("Automorphic Number")
else:
    print("Not an Automorphic Number")

#33
n = int(input())
arr = list(map(int, input().split()))
total = n * (n + 1) // 2
print(total - sum(arr))

#34
arr = list(map(int, input().split()))
seen = []
for x in arr:
    if x in seen:
        break
    seen.append(x)
if duplicate:
    print("Duplicate Found")
else:
    print("No Duplicate")

#35
t = int(input())
for i in range(0,t):
    a,b = map(int,input().split())
    print(a+b)

#36
t = int(input())
for i in range(0,t):
    a,b = map(int,input().split())
    print(a%b)
#37
    n=int(input())
for i in range(0,n):
    N=int(input())
    l=list(map(int,input().split()))
    r=list(map(int,input().split()))
    s=[]
    a=[]
    for j in range(0,N):
        s.append(l[j]*r[j])
    for k in range(0,N):
        if(s[k]==max(s)):
            a.append(r[k])
    ma=max(a)
    for k in range(0,N):
        if(r[k]==ma):
            print(k+1)
            break
#38
(n, k) = map(int, input().split())

ans = 0

for i in range(n):
	x = int(input())
	if x % k == 0:
		ans += 1

print(ans)	
#39
t=int(input())
for _ in range(t):
    n=int(input())
    print(int(n**0.5))
#40
t=int(input())
for _ in range(t):
    n=input()
    total=0
    for ch in n:
        total += int(ch)
    print(total)
#41
x,y = map(int,input().split())
if y > x:
    print("Yes")
else:
    print("No")
#42
x,y = map(int,input().split())
if x >= 2*y:
    print("Yes")
else:
    print("No")
#43
    a,b = map(int,input().split())
if a+b+(a*b) == 111:
    print("Yes")
else:
    print("No")
#44
    n,a,b = map(int,input().split())
rated_users = n - a 
high_rated_users = rated_users - b
print(rated_users,high_rated_users)
#45
n = int(input())
cell=(n*n) // 2
print(cell)
#46
a,b = map(int,input().split())
sum_val = a+b
prod_val = a*b
ans=prod_val - sum_val
print(abs(ans))
#47
t=int(input())
listsal=[]
sal=0
hra=0
da=0
gross=0
for _ in range(t):
    sal=int(input())
    listsal.append(sal)
for salary in listsal:
    if(salary<1500):
        hra=(10*salary)/100
        da=(90*salary)/100
    elif(salary>=1500):
        hra=500
        da=(98*salary)/100
    gross=salary+hra+da
    print(gross)
#48
    t=int(input())
for _ in range(t):
    a,b,c = list(map(int,input().split()))
    if (a+b+c) == 180:
        print("YES")
    else:
        print("NO")
#49
        t=int(input())
for _ in range(t):
    h,c,t=list(map(float,input().split()))
    if(h>50 and c<0.7 and t>5600):
        print(10)
    elif(h>50 and c<0.7):
        print(9)
    elif(c<0.7 and t>5600):
        print(8)
    elif(h>50 and t>5600):
        print(7)
    elif(h>50 or c<0.7 or t>5600):
        print(6)
    elif not(h>50 or c<0.7 or t>5600):
        print(5)
#50
t=int(input())
inp=""
listv=[]
for _ in range(t):
    inp=input()
    listv.append(inp)
for it in listv:
    if(it=='b' or it=='B'):
        print("BattleShip")
    if(it=='C' or it=='c'):
        print("Cruiser")
    if(it=='D' or it=='d'):
        print("Destroyer")
    if(it=='f' or it=='F'):
        print("Frigate")

#51
t=int(input())
for _ in range(t):
    quantity, price = map(int, input().split())
    total = quantity*price
    if quantity > 1000 :
        total = total - (0.10 * total )
    print(f"{total:.6f}")
#52
t=int(input())
for _ in range(t):
    A,B,C = map(int,input().split())
    numbers = [A ,B,C]
    numbers.sort()
    print(numbers[1])
#53
n=int(input())
ready=0
notready=0
num=list(map(int,input().split()))
for i in num:
    if(i%2==0):
        ready+=1
    else:
        notready+=1
if n==1:
    print("READY FOR BATTLE")
elif(ready>notready):
    print("READY FOR BATTLE")
else:
    print("NOT READY")
#54
t=int(input())
for _ in range(t):
    n=input()
    reverse=n[::-1]
    print(int(reverse))
#55
t=int(input())
for _ in range(t):
    n=input()
    if n == n[::-1]:
        print("wins")
    else:
        print("loses")
#56
t=int(input())
for _ in range(t):
    n=input()
    count=0
    for i in n:
        if i == '4':
            count+=1
    print(count)
#57
t=int(input())
for _ in range(t):
    n=int(input())
    fact=1
    for i in range(1,n+1):
        fact*=i
    print(fact)
#58
while True:
    n=int(input())
    if n==42:
        break
    print(n)
#59
t=int(input())
for _ in range(t):
    n=int(input())
    s=input()
    count_a=s.count('a')
    count_b=s.count('b')
    print(count_a,count_b)
#60
t=int(input())
for _ in range(t):
    X,Y,K,N=list(map(int,input().split()))
    req_pages=X-Y
    found= False
    for _ in range(N):
        P, C = map(int, input().split())
        if P >= req_pages and C <= K:
            found = True
    if found:
        print("LuckyChef")
    else:
        print("UnluckyChef")
#61
N = int(input())

score_1 = 0
score_2 = 0
max_lead = 0
winner = 0

for _ in range(N):

    s1, s2 = map(int, input().split())
    

    score_1 += s1
    score_2 += s2
    

    if score_1 > score_2:
        lead = score_1 - score_2
        current_winner = 1
    else:
        lead = score_2 - score_1
        current_winner = 2
    

    if lead > max_lead:
        max_lead = lead
        winner = current_winner

print(winner, max_lead)
#62
t=int(input())
for _ in range(t):
    N, K = map(int,input().split())
    values=list(map(int,input().split()))
    count=0
    for value in values:
        if (value + K) % 7 == 0 :
            count+=1
    print(count)
#63
K, N = map(int, input().split())

favorites = [input().strip() for _ in range(K)]

for _ in range(N):
    found_string = input().strip()

    if len(found_string) >= 47:
        print("Good")
    else:

        is_good = any(fav in found_string for fav in favorites)
        print("Good" if is_good else "Bad")
#64
        T = int(input())
for _ in range(T):
    N, M = map(int, input().split())
    alice_numbers = set(map(int, input().split()))
    berta_numbers = set(map(int, input().split()))
    common_numbers = alice_numbers.intersection(berta_numbers)
    print(len(common_numbers))
#65

T = int(input())
results = []
for _ in range(T):
    N = int(input())
    arr = list(map(int, input().split()))
    if N < 7:
        results.append("no")
        continue
    left, right, expected_num = 0, N - 1, 1
    is_rainbow = True
    while left <= right:
        if arr[left] != arr[right] or arr[left] < 1 or arr[left] > 7:
            is_rainbow = False
            break
        if arr[left] != expected_num:
            if arr[left] == expected_num + 1:
                expected_num += 1
            else:
                is_rainbow = False
                break
        left += 1
        right -= 1
    results.append("yes" if is_rainbow and expected_num == 7 else "no")
print("\n".join(results))

#66
name = input("Student Name: ")
marks = list(map(int, input("Enter marks: ").split()))
total = sum(marks)
average = total / len(marks)
highest = max(marks)
status = "Pass"
for i in marks:
    if i < 35:
        status = "Fail"
        break
print("Total:", total)
print("Average:", average)
print("Highest Mark:", highest)
print("Status:", status)

#67
name = input("Employee Name: ")
scores = list(map(int, input("Enter scores: ").split()))
best = max(scores)
avg = sum(scores) / len(scores)
count = 0
for i in scores:
    if i > 80:
        count += 1
print("Best Score:", best)
print("Average Score:", round(avg, 1))
print("Months Above 80:", count)

#68
vehicles = [101, 105, 110, 101, 115, 105]
duplicates = []
for i in vehicles:
    if vehicles.count(i) > 1 and i not in duplicates:
        duplicates.append(i)
unique = []
for i in vehicles:
    if i not in unique:
        unique.append(i)
print("Duplicate Vehicles:", duplicates)
print("Unique Vehicles:", len(unique))

#69
player = input("Player: ")
scores = list(map(int, input("Enter scores: ").split()))
highest = max(scores)
lowest = min(scores)
average = sum(scores) / len(scores)
half_centuries = 0
for i in scores:
    if i >= 50:
        half_centuries += 1
print("Highest Score:", highest)
print("Lowest Score:", lowest)
print("Average Score:", round(average, 1))
print("Half Centuries:", half_centuries)

#70
prices = [1200, 3500, 800, 1500]
total_bill = 0
for price in prices:
    total_bill += price
costliest_item = prices[0]
for price in prices:
    if price > costliest_item:
        costliest_item = price
if total_bill > 5000:
    discounted_bill = total_bill - (total_bill * 15 / 100)
else:
    discounted_bill = total_bill
print("Total Bill:", total_bill)
print("Costliest Item:", costliest_item)
print("Discounted Bill:", int(discounted_bill))

#71
patient = input("Name: ")
n = int(input("temperature readings: "))
temperatures = []
for i in range(n):
    temp = float(input("Enter temperature: "))
    temperatures.append(temp)
highest = temperatures[0]
lowest = temperatures[0]
abnormal = 0
for temp in temperatures:
    if temp > highest:
        highest = temp
    if temp < lowest:
        lowest = temp
    if temp > 100:
        abnormal += 1
print("Highest Temperature:", highest)
print("Lowest Temperature:", lowest)
print("Abnormal Readings:", abnormal)

#72
booked = [1, 3, 5, 7, 10, 15]
print("Total Booked Seats:", len(booked))
available = []
for seat in range(1, 21):
    if seat not in booked:
        available.append(seat)
print("Available Seats:")
print(available)

#73
attendance = [85, 70, 92, 65, 78, 88]
highest = attendance[0]
lowest = attendance[0]
eligible = 0
for a in attendance:
    if a > highest:
        highest = a
    if a < lowest:
        lowest = a
    if a >= 75:
        eligible += 1
print("Highest Attendance:", highest)
print("Lowest Attendance:", lowest)
print("Eligible Students:", eligible)

#74
#second largest number without sort
numbers = [12, 45,  23, 89, 67]
largest = numbers[0]
second = numbers[0]
for i in numbers:
    if i > largest:
        second = largest
        largest = i
    elif i > second and i != largest:
        second = i
print("Second Largest:",second)

#75
s = "swiss"
for ch in s:
    if s.count(ch) == 1:
        print("unique:", ch)
        break
		
#76
L = [1,2,3,4,5]
k=2
result = L[-k:] + L[:-k]
print(result)

#78
numbers = [7, 2, 5, 4, 9, 8]
result = []
for i in numbers:
    if i % 2 == 0:
        result.append(i)
for i in numbers:
    if i % 2 != 0:
        result.append(i)
print(result)

#79
s = input()
for ch in "aeiouAEIOU":
    s = s.replace(ch, "")
print("Consonants:", s)
print("Length", len(s))

#80
arr = [2, 7, 11, 15, 3, 6]
tar = 9
for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] + arr[j] == tar:
            print("(", arr[i], ",", arr[j], ")", sep="")

#81
L = [1, [2, 3], [4, [5, 6]]]
total = L[0] + L[1][0] + L[1][1] + L[2][0] + L[2][1][0] + L[2][1][1]
print(total)

#82
x=[1,[2,3],[4,[5,6]]]
t=0
for i in x:
  if isinstance(i, list):
    for j in i:
      if isinstance(j, list):
        for k in j:
          t += k
      else:
        t += j
  else:
    t += i
print(t)

#83
for i in range(1, 101):
    if i < 10:
        print(i, end=" ")
    else:
        a = i // 10
        b = i % 10
        if a + b == a * b:
            print(i, end=" ")
