# -*- coding: utf-8 -*-
"""studentperformanceanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wmY-IWuqoMZP4o9DtkFrCC-Vw0-Q_IJ
"""

import os
os.environ['KAGGLE_USERNAME'] = 'laks'
os.environ['KAGGLE_KEY'] = 'KGAT_10e8f6e689459d44f41108d4374a8017'

!pip install kaggle

!kaggle datasets download -d grandmaster07/student-exam-performance-dataset-analysis

!unzip /content/student-exam-performance-dataset-analysis.zip -d /content/student

import pandas as pd
df = pd.read_csv("/content/student-exam-performance-dataset-analysis.zip")
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

print(df.columns)

print(df['Gender'])

df.drop('Family_Income', axis=1, inplace=True)
print(df)

print(df['Previous_Scores'].median())

df.isnull().sum()

df['Teacher_Quality'].fillna(df['Teacher_Quality'].mode()[0], inplace=True)
print(df[['Teacher_Quality']].head(10))
print(df['Teacher_Quality'].isnull().sum())

df['Parental_Education_Level'].fillna(df['Parental_Education_Level'].mode()[0], inplace=True)
print(df[['Parental_Education_Level']].head(10))
print(df['Parental_Education_Level'].isnull().sum())

df['Distance_from_Home'].fillna(df['Distance_from_Home'].mode()[0], inplace=True)
print(df[['Distance_from_Home']].head(10))
print(df['Distance_from_Home'].isnull().sum())

df.drop_duplicates(inplace=True)
print(df)

df.head()
df.info()

df.drop(['Parental_Education_Level', 'Distance_from_Home'], axis=1, inplace=True)

df.isnull().sum()

import matplotlib.pyplot as plt
plt.hist(df['Attendance'], bins=10, color='skyblue', edgecolor='black')
plt.title('Distribution of Attendance')
plt.xlabel('Attendance')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt

plt.boxplot(df['Exam_Score'])
plt.title('Outlier Detection using Boxplot (Exam_Score)')
plt.ylabel('Exam_Score')
plt.show()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

print(df.head())

X = df.drop('Exam_Score', axis=1)
y = df['Exam_Score']
print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
print("Model Trained Successfully")

y_pred = model.predict(X_test)
print(y_pred[:10])

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

from sklearn.metrics import confusion_matrix

y_pred_rounded = y_pred.round().astype(int)
cm = confusion_matrix(y_test, y_pred_rounded)

print("Confusion Matrix:")
print(cm)

from sklearn.metrics import classification_report
y_pred_rounded = y_pred.round().astype(int)
print(classification_report(y_test, y_pred_rounded))